// FILE GENERATED BY FlutterFire CLI
// This is a placeholder file - you need to run flutterfire configure to generate the actual config

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// TO GENERATE THIS FILE:
/// 1. Create a Firebase project at https://console.firebase.google.com
/// 2. Install FlutterFire CLI: dart pub global activate flutterfire_cli
/// 3. Run: flutterfire configure
/// 
/// This will automatically generate this file with your Firebase config.
class DefaultFirebaseOptions {
  static bool _isPlaceholder(String? value) =>
      value == null || value.isEmpty || value.startsWith('YOUR_');

  /// True if firebase_options still has placeholder values (flutterfire configure not run).
  /// When true, main.dart will call Firebase.initializeApp() without options so that
  /// platform config (google-services.json, GoogleService-Info.plist) is used instead.
  static bool get hasPlaceholderValues =>
      _isPlaceholder(web.projectId) ||
      _isPlaceholder(web.apiKey) ||
      _isPlaceholder(android.apiKey) ||
      _isPlaceholder(android.appId) ||
      _isPlaceholder(ios.apiKey) ||
      _isPlaceholder(ios.appId);

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase config
  // Run `flutterfire configure` to generate the real values

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkYqpAqXuqZiDvWf4snHE4wITMioVqFg8',
    appId: '1:1020739823021:web:f49c75f35ae6295debad24',
    messagingSenderId: '1020739823021',
    projectId: 'fblamobileappdevelopment-e6b54',
    authDomain: 'fblamobileappdevelopment-e6b54.firebaseapp.com',
    storageBucket: 'fblamobileappdevelopment-e6b54.firebasestorage.app',
    measurementId: 'G-Z52SQJJJKM',
  );

  

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTM9KgVEBv8E-kvNezV1VSxjIr2K1lrMQ',
    appId: '1:1020739823021:android:c2c2a63f5642efeeebad24',
    messagingSenderId: '1020739823021',
    projectId: 'fblamobileappdevelopment-e6b54',
    storageBucket: 'fblamobileappdevelopment-e6b54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoDCuvHjEdHASM6gOVgXZhaPgjEQj3Vmg',
    appId: '1:1020739823021:ios:e74512e73b99409debad24',
    messagingSenderId: '1020739823021',
    projectId: 'fblamobileappdevelopment-e6b54',
    storageBucket: 'fblamobileappdevelopment-e6b54.firebasestorage.app',
    iosBundleId: 'com.example.fblaMemberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoDCuvHjEdHASM6gOVgXZhaPgjEQj3Vmg',
    appId: '1:1020739823021:ios:e74512e73b99409debad24',
    messagingSenderId: '1020739823021',
    projectId: 'fblamobileappdevelopment-e6b54',
    storageBucket: 'fblamobileappdevelopment-e6b54.firebasestorage.app',
    iosBundleId: 'com.example.fblaMemberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkYqpAqXuqZiDvWf4snHE4wITMioVqFg8',
    appId: '1:1020739823021:web:003e7bfd02573d93ebad24',
    messagingSenderId: '1020739823021',
    projectId: 'fblamobileappdevelopment-e6b54',
    authDomain: 'fblamobileappdevelopment-e6b54.firebaseapp.com',
    storageBucket: 'fblamobileappdevelopment-e6b54.firebasestorage.app',
    measurementId: 'G-F8K2HW57S5',
  );

}